/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHMQuiz.classes.Anime;

import IHMQuiz.classes.SelectQuiz;
import javax.swing.JButton;

/**
 *
 * @author Joe
 */
public class Anime extends javax.swing.JFrame {

    /**
     * Creates new form Musique
     * @param diff
     */
    public Anime(int diff) {
        initComponents();
        this.difficulty=diff;
    }
    public int solution;
    public int score =0;
    public int currquestion=1;
    public int difficulty=1;
    
    
    public void resetScore(){
        score=0;
        jLabel3.setText("SCORE: "+score);
        currquestion=1;
        changeQuestionLabelText(currquestion+"/5");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMQuiz/Back.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setFocusable(false);
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 255, 255));
        jButton5.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 255, 255));
        jButton7.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 580));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMQuiz/AnimeBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        SelectQuiz a = new SelectQuiz();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setResizable(false);
        a.setVisible(true);
     
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        		if (solution == 1) {

				score= score+10;
                                currquestion++;
                                changeQuestionLabelText(currquestion+"/5");
                                                                jLabel3.setText("SCORE: "+score);
                                end();                    
                                if(difficulty == 0)
				AnimeQuestionChanger.newEasyQuestion();
                                else {
                                if(difficulty == 1)
				AnimeQuestionChanger.newNormalQuestion();
                                else
				AnimeQuestionChanger.newHardQuestion();
                                }
				
			} else {
		
                               

				currquestion++;
                                changeQuestionLabelText(currquestion+"/5");
                                end();
                                 if(difficulty == 0)
				AnimeQuestionChanger.newEasyQuestion();
                                else {
                                if(difficulty == 1)
				AnimeQuestionChanger.newNormalQuestion();
                                else
				AnimeQuestionChanger.newHardQuestion();
                                }
			}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (solution == 2) {

				score= score+10;
                                
                                currquestion++;
                                 changeQuestionLabelText(currquestion+"/5");
                                                                 jLabel3.setText("SCORE: "+score);
                                end();
                                 if(difficulty == 0)
				AnimeQuestionChanger.newEasyQuestion();
                                else {
                                if(difficulty == 1)
				AnimeQuestionChanger.newNormalQuestion();
                                else
				AnimeQuestionChanger.newHardQuestion();
                                }
				
			} else {

				
                                
                                currquestion++;
                                 changeQuestionLabelText(currquestion+"/5");
                                end();
                                 if(difficulty == 0)
				AnimeQuestionChanger.newEasyQuestion();
                                else {
                                if(difficulty == 1)
				AnimeQuestionChanger.newNormalQuestion();
                                else
				AnimeQuestionChanger.newHardQuestion();
                                }
			}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (solution == 4) {
				
				score= score+10;
                                
                                currquestion++;
                                 changeQuestionLabelText(currquestion+"/5");
                                                                 jLabel3.setText("SCORE: "+score);
                                end();
                                 if(difficulty == 0)
				AnimeQuestionChanger.newEasyQuestion();
                                else {
                                if(difficulty == 1)
				AnimeQuestionChanger.newNormalQuestion();
                                else
				AnimeQuestionChanger.newHardQuestion();
                                }
				
			} else {
		
                                
                                currquestion++;
                                changeQuestionLabelText(currquestion+"/5");
                                end();
                                if(difficulty == 0)
				AnimeQuestionChanger.newEasyQuestion();
                                else {
                                if(difficulty == 1)
				AnimeQuestionChanger.newNormalQuestion();
                                else
				AnimeQuestionChanger.newHardQuestion();
                                }
			}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (solution == 3) {
				
				score= score+10;

                                
                                currquestion++;
                                changeQuestionLabelText(currquestion+"/5");
                                                                jLabel3.setText("SCORE: "+score);
                                end();
                                if(difficulty == 0)
				AnimeQuestionChanger.newEasyQuestion();
                                else {
                                if(difficulty == 1)
				AnimeQuestionChanger.newNormalQuestion();
                                else
				AnimeQuestionChanger.newHardQuestion();
                                }
                                
				
			} else {
	
				
                                
                                currquestion++;
                                changeQuestionLabelText(currquestion+"/5");
                                
                                end();
                                 if(difficulty == 0)
				AnimeQuestionChanger.newEasyQuestion();
                                else {
                                if(difficulty == 1)
				AnimeQuestionChanger.newNormalQuestion();
                                else
				AnimeQuestionChanger.newHardQuestion();
                                }
			}
    }//GEN-LAST:event_jButton7ActionPerformed
    public void changeLabelText(String text) {
		jLabel1.setText(text);
	}
    public void changeQuestionLabelText(String text) {
		jLabel4.setText(text);
	}
    public void changeButtonText(JButton button, String text) {
		button.setText(text);
	}
    public void end(){
        if(currquestion==6){
            AnimeScorePage scorePage = new AnimeScorePage();
            scorePage.setLocationRelativeTo(null);
            scorePage.setVisible(true);
            scorePage.setResizable(false);
            scorePage.setScoreText(score);
            this.dispose();
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*new QuestionChanger();
        this.dispose();*/
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musique().setVisible(true);
                
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
