/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHMQuiz.classes;

import IHMQuiz.classes.Anime.AnimeQuestionChanger;
import IHMQuiz.classes.Informatique.CSQuestionChanger;
import IHMQuiz.classes.JV.JVQuestionChanger;
import IHMQuiz.classes.Musique.MusicQuestionChanger;
import IHMQuiz.classes.Sante.SanteQuestionChanger;
import IHMQuiz.classes.SelectQuiz;
import IHMQuiz.classes.Sport.SportQuestionChanger;

/**
 *
 * @author Joe
 */
public class Difficulty extends javax.swing.JFrame {

    /**
     * Creates new form MusicDifficulty
     */
    int theme = 0;
    public Difficulty(int theme) {
        this.theme = theme;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMQuiz/Easy.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FACILE");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMQuiz/Normal.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INTERMÉDIAIRE");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMQuiz/Hard.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DIFFICILE");

        jLabel4.setFont(new java.awt.Font("Open Sans", 2, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VEUILLEZ SÉLECTIONNER LA DIFFICULTÉ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 86, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMQuiz/Back.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IHMQuiz/MainPage.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        SelectQuiz a =  new SelectQuiz();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        switch (theme) {
            case 1:
                MusicQuestionChanger musicQuestionChanger;
                musicQuestionChanger = new MusicQuestionChanger(0);
                musicQuestionChanger.difficulty = 0;
                this.dispose();
                     break;
            case 2:  
                JVQuestionChanger jvQuestionChanger;
                jvQuestionChanger = new JVQuestionChanger(0);
                jvQuestionChanger.difficulty = 0;
                this.dispose();
                     break;
            case 3:  
                CSQuestionChanger csQuestionChanger;
                csQuestionChanger = new CSQuestionChanger(0);
                csQuestionChanger.difficulty = 0;
                this.dispose();
                     break;
            case 4:  
                AnimeQuestionChanger animeQuestionChanger;
                animeQuestionChanger = new AnimeQuestionChanger(0);
                animeQuestionChanger.difficulty = 0;
                this.dispose();
                     break;
            case 5:  
                SanteQuestionChanger santeQuestionChanger;
                santeQuestionChanger = new SanteQuestionChanger(0);
                santeQuestionChanger.difficulty = 0;
                this.dispose(); 
                     break;
            case 6:  
                SportQuestionChanger sportQuestionChanger;
                sportQuestionChanger = new SportQuestionChanger(0);
                sportQuestionChanger.difficulty = 0;
                this.dispose(); 
                     break;
            default: 
                     break;
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        switch (theme) {
            case 1:
                MusicQuestionChanger musicQuestionChanger;
                musicQuestionChanger = new MusicQuestionChanger(1);
                musicQuestionChanger.difficulty = 1;
                this.dispose();
                     break;
            case 2:  
                JVQuestionChanger jvQuestionChanger;
                jvQuestionChanger = new JVQuestionChanger(1);
                jvQuestionChanger.difficulty = 1;
                this.dispose();
                     break;
            case 3:  
                CSQuestionChanger csQuestionChanger;
                csQuestionChanger = new CSQuestionChanger(1);
                csQuestionChanger.difficulty = 1;
                this.dispose();
                     break;
            case 4:  
                               AnimeQuestionChanger animeQuestionChanger;
                animeQuestionChanger = new AnimeQuestionChanger(1);
                animeQuestionChanger.difficulty = 1;
                this.dispose(); 
                     break;
            case 5:  
                SanteQuestionChanger santeQuestionChanger;
                santeQuestionChanger = new SanteQuestionChanger(1);
                santeQuestionChanger.difficulty = 1;
                this.dispose(); 
                     break;
            case 6:  
                SportQuestionChanger sportQuestionChanger;
                sportQuestionChanger = new SportQuestionChanger(1);
                sportQuestionChanger.difficulty = 1;
                this.dispose(); 
                     break;
            default: 
                     break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        switch (theme) {
            case 1:
                MusicQuestionChanger musicQuestionChanger;
                musicQuestionChanger = new MusicQuestionChanger(2);
                musicQuestionChanger.difficulty = 2;
                this.dispose();
                     break;
            case 2:  
                JVQuestionChanger jvQuestionChanger;
                jvQuestionChanger = new JVQuestionChanger(2);
                jvQuestionChanger.difficulty = 2;
                this.dispose();
                     break;
            case 3: 
                CSQuestionChanger csQuestionChanger;
                csQuestionChanger = new CSQuestionChanger(2);
                csQuestionChanger.difficulty = 2;
                this.dispose();
                     break;
            case 4:  
                AnimeQuestionChanger animeQuestionChanger;
                animeQuestionChanger = new AnimeQuestionChanger(2);
                animeQuestionChanger.difficulty = 2;
                this.dispose();
                     break;
            case 5:  
                SanteQuestionChanger santeQuestionChanger;
                santeQuestionChanger = new SanteQuestionChanger(2);
                santeQuestionChanger.difficulty = 2;
                this.dispose(); 
                     break;
            case 6:  
                SportQuestionChanger sportQuestionChanger;
                sportQuestionChanger = new SportQuestionChanger(2);
                sportQuestionChanger.difficulty = 2;
                this.dispose(); 
                     break;
            default: 
                     break;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Difficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create a//<editor-fold defaultstate="collapsed" desc="comment">
        n
        //</editor-fold>
d display the form */
        /*
      java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Runnable runnable = () -> {
                    Difficulty a = new Difficulty();
                    a.setVisible(true);
                    a.setLocationRelativeTo(null);
                };
            }
        }); */
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
